version: "3.7"

services:
  pastebin:
    image: trgwii/deno-pastebin
    container_name: trgwii_deno_pastebin
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /deno-dir/
    command: run --allow-net --allow-read=pastes --allow-write=pastes https://git.rory.no/trgwii/pastebin/raw/branch/master/serve.ts
    ports:
      - "8080:8080"
    volumes:
       - ./pastes:/deno-dir/pastes
